#!/bin/bash

# Script para Configurar Stripe em Produção para Fixelo
# Execute este script após configurar suas chaves do Stripe

echo "🚀 CONFIGURAÇÃO STRIPE PARA FIXELO EM PRODUÇÃO"
echo "=============================================="

# Verificar se as chaves estão configuradas
if [ -z "$STRIPE_SECRET_KEY" ]; then
    echo "❌ STRIPE_SECRET_KEY não encontrada nas variáveis de ambiente"
    echo "Configure suas chaves do Stripe no arquivo .env.production"
    exit 1
fi

echo "✅ Chaves do Stripe encontradas"
echo "🔄 Criando produtos e preços no Stripe..."

# Executar script de criação de produtos
node create-stripe-products.js

echo ""
echo "📋 INSTRUÇÕES PARA CONFIGURAR STRIPE DASHBOARD:"
echo ""
echo "1. 🌐 Acesse: https://dashboard.stripe.com/"
echo "2. 🔑 Configure suas chaves de produção:"
echo "   - Vá em Developers > API keys"
echo "   - Copie a Secret key (sk_live_...)"
echo "   - Copie a Publishable key (pk_live_...)"
echo ""
echo "3. 🔗 Configure Webhooks:"
echo "   - Vá em Developers > Webhooks"
echo "   - Clique em 'Add endpoint'"
echo "   - URL: https://api.fixelo.app/api/v1/stripe/webhook"
echo "   - Eventos para escutar:"
echo "     * customer.subscription.created"
echo "     * customer.subscription.updated"
echo "     * customer.subscription.deleted"
echo "     * invoice.payment_succeeded"
echo "     * invoice.payment_failed"
echo "     * checkout.session.completed"
echo ""
echo "4. 📱 Configure Produtos (Planos de Assinatura):"
echo ""
echo "   📦 PLANO FREE (Gratuito):"
echo "   - Nome: Fixelo Free Plan"
echo "   - Descrição: Plan gratuito para prestadores de serviço"
echo "   - Preço: $0/mês"
echo "   - Benefícios:"
echo "     * Até 10 leads/mês"
echo "     * Perfil básico"
echo "     * Avaliações de clientes"
echo "     * Leads extras: $3 cada"
echo ""
echo "   💎 PLANO PRO:"
echo "   - Nome: Fixelo Pro Plan"
echo "   - Descrição: Plano profissional para prestadores de serviço"
echo "   - Preço Mensal: $34.80/mês"
echo "   - Preço Anual: $334.08/ano (20% desconto)"
echo "   - Benefícios:"
echo "     * Leads e mensagens ilimitados"
echo "     * Badge verificado"
echo "     * Visibilidade top nas buscas"
echo "     * Dashboard de analytics"
echo "     * Acesso a boost/ads"
echo "     * Suporte prioritário"
echo "     * 7 dias de teste grátis"
echo ""
echo "5. 💰 Configure Taxa da Plataforma:"
echo "   - 5% de taxa em todas as transações"
echo "   - Configure no Stripe Connect (se usando)"
echo ""
echo "6. 🔔 Configure Notificações:"
echo "   - Email para falhas de pagamento"
echo "   - SMS para alertas críticos"
echo ""
echo "7. 📊 Configure Analytics:"
echo "   - Stripe Sigma para relatórios avançados"
echo "   - Webhooks para sincronizar com dashboard interno"
echo ""
echo "📝 VARIÁVEIS DE AMBIENTE NECESSÁRIAS:"
echo ""
echo "Após criar os produtos, adicione no .env.production:"
echo "STRIPE_SECRET_KEY=sk_live_..."
echo "STRIPE_PUBLISHABLE_KEY=pk_live_..."
echo "STRIPE_WEBHOOK_SECRET=whsec_..."
echo "STRIPE_FREE_PRODUCT_ID=prod_..."
echo "STRIPE_PRO_PRODUCT_ID=prod_..."
echo "STRIPE_PRO_MONTHLY_PRICE_ID=price_..."
echo "STRIPE_PRO_YEARLY_PRICE_ID=price_..."
echo ""
echo "🔒 SEGURANÇA:"
echo "- Nunca exponha as chaves secretas (sk_live_)"
echo "- Use HTTPS em todos os endpoints"
echo "- Valide webhooks com assinatura"
echo "- Configure rate limiting nos endpoints"
echo ""
echo "🧪 TESTE EM PRODUÇÃO:"
echo "curl -X POST https://api.fixelo.app/api/v1/stripe/create-checkout-session \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -H 'Authorization: Bearer YOUR_JWT_TOKEN' \\"
echo "  -d '{\"priceId\": \"price_pro_monthly_id\"}'"
echo ""
echo "✅ Configuração concluída!"
echo "Acesse https://dashboard.stripe.com para finalizar a configuração"
